development:
  adapter: postgresql
  encoding: unicode
  database: lims_development
  pool: 5
  username: <%= ENV['matt'] %>
  password: <%= ENV['B00thbay'] %>
  min_messages: WARNING
  template: template0  #template0 resolves an issue with SQL_ASCII vs UTF-8 encoding
  host: localhost

test:
  adapter: postgresql
  encoding: unicode
  database: lims_test
  template: template0
  pool: 5
  username: matt
  password: B00thbay
  min_messages: WARNING
  host: localhost

production:
  adapter: postgresql
  encoding: unicode
  database: lims_production
  pool: 5
  username: deployer
  password:
  min_messages: WARNING
  template: template0
